apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx-server
  template:
    metadata:
      name: nginx-server
      labels: 
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: nginx:1.14.2
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-server-service
  labels: 
    app: nginx-server
spec:
  type: LoadBalancer
  selector:
    app: nginx-server
  ports:
    - port: 80